name: test name

on:
  workflow_dispatch:

env:
  CONFIG_FILE: test.config

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Load custom configuration
      run: |
        ls -al
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE .config
        echo "复制文件后"
        ls -al
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        echo "创建DEVICE_NAME后"
        ls -al
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "检测文件命令执行，尝试输出GITHUB_ENV"
        echo "${{ env.DEVICE_NAME }}"
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "${{ env.FILE_DATE }}"
